In [1]:
import numpy as matrix

# MATRIX 
## it is an array of 2d array or 2dlist 

In [45]:
Matrix = matrix.arange(8).reshape(2,4)
Matrix2 = matrix.linspace(0,10,8).reshape(2,4)
print "Og MATRIX IS ", Matrix
print 
print "2 Og MATRIX IS ", Matrix2

Og MATRIX IS  [[0 1 2 3]
 [4 5 6 7]]

2 Og MATRIX IS  [[ 0.          1.42857143  2.85714286  4.28571429]
 [ 5.71428571  7.14285714  8.57142857 10.        ]]


In [46]:
def matrix_operations(m1,m2):
    addi=matrix.add(m1,m2)
    print "Addition is ",addi
    print
    sub=matrix.subtract(m1,m2)
    print "Subtraction is ",sub
    print
    mul=matrix.multiply(m1,m2)
    print "Multiplication  is ",mul
    print
    div=matrix.divide(m1,m2)
    print "Division is ",div
    print
    sqroot=matrix.sqrt(m1,m2)
    print "Square root of each element  is ",sqroot
    print
    summ_total=matrix.sum(m1)
    print "summesion of all elements is ",summ_total
    print
    summ_0=matrix.sum(m1,axis=0)
    print "Summesion of column elements is ",summ_0
    print
    summ_1=matrix.sum(m1,axis=1)
    print "Summesion of all row elements is ",summ_1
    print
    Transopse=m1.T
    print "Transpostion  ",summ_0
    print
    Transopse=m2.T
    print "Transpostion  ",summ_0
matrix_operations(Matrix,Matrix2)
    
    

Addition is  [[ 0.          2.42857143  4.85714286  7.28571429]
 [ 9.71428571 12.14285714 14.57142857 17.        ]]

Subtraction is  [[ 0.         -0.42857143 -0.85714286 -1.28571429]
 [-1.71428571 -2.14285714 -2.57142857 -3.        ]]

Multiplication  is  [[ 0.          1.42857143  5.71428571 12.85714286]
 [22.85714286 35.71428571 51.42857143 70.        ]]

Division is  [[nan 0.7 0.7 0.7]
 [0.7 0.7 0.7 0.7]]

Square root of each element  is  [[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]]

summesion of all elements is  28

Summesion of column elements is  [ 4  6  8 10]

Summesion of all row elements is  [ 6 22]

Transpostion   [ 4  6  8 10]

Transpostion   [ 4  6  8 10]


C:\ProgramData\Anaconda2\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in divide
  # This is added back by InteractiveShellApp.init_path()


In [47]:
len(Matrix)

2

In [48]:
len(Matrix[0])

4

In [49]:
suum=0
for i in Matrix:
    print(i)
    for j in i:
        print(j)
        suum=suum+j
        j=j+1
print(suum)

[0 1 2 3]
0
1
2
3
[4 5 6 7]
4
5
6
7
28


In [50]:
print(max(i))
print(max(i)-1)

7
6


In [2]:
##matlib
import numpy.matlib as MATLIB

In [3]:
out_mat = MATLIB.empty((2, 3))  
print ("Output matrix : ", out_mat)

('Output matrix : ', matrix([[1.58010682e-316, 1.58176144e-316, 7.74729885e-315],
        [3.34385250e-316, 0.00000000e+000, 0.00000000e+000]]))


In [4]:
## EYE same as array
matr=MATLIB.eye(4,4,k=0,dtype=int,order="F")
print(matr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [5]:
# Program to add two matrices using nested loop

X = [[1,2,3],[4 ,5,6],[7 ,8,9]]

Y = [[9,8,7],[6,5,4],[3,2,1]]


result = [[0,0,0],[0,0,0],[0,0,0]]

# iterate through rows
for i in range(len(X)): 
# iterate through columns
    for j in range(len(X[0])):
        result[i][j] = X[i][j] + Y[i][j]

for r in result:
    print(r)

    
print("whle in list ccomprehension [first add element of X,Y then len(X[0]) and then len(X)]")

[10, 10, 10]
[10, 10, 10]
[10, 10, 10]
whle in list ccomprehension [first add element of X,Y then len(X[0]) and then len(X)]


In [6]:
identity_matrix = MATLIB.identity(5,dtype=int)
print(identity_matrix)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
