In [1]:
import numpy as np 

In [3]:
np.__version__

'1.14.0'

In [4]:
arr = np.array([1,2,2,3,4,5])
print arr

[1 2 2 3 4 5]


In [5]:
type(arr)

numpy.ndarray

In [7]:
# converting tuple to array tup=np.array()
tup = np.array((1,2,2,3,4,5))
print type(tup)

<type 'numpy.ndarray'>


In [2]:
arr1d = np.array([1,2,2,3,4,5])
print arr1d
arr2d = np.array([[1,2,2,3,4,5],[6,7,8,9,10]])
print arr2d
arr3d = np.array([[1,2,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print arr3d
higherdim_arr= np.array([1,2,2,3,4,5])
print higherdim_arr

[1 2 2 3 4 5]
[list([1, 2, 2, 3, 4, 5]) list([6, 7, 8, 9, 10])]
[list([1, 2, 2, 3, 4, 5]) list([6, 7, 8, 9, 10])
 list([11, 12, 13, 14, 15])]
[1 2 2 3 4 5]


In [6]:
arr = np.array([1,2,2,3,4,5])
arr2=np.array([[1,2,3,5],[4,5,6,8]])
print arr2.shape
print arr2.size
print arr

print "No of dim of arr",arr.ndim
print "shape of arr",arr.shape
print "Size of arr",arr.size
print "data type  of arr",arr.ndim

print "Length of array is ",len(arr)

(2L, 4L)
8
[1 2 2 3 4 5]
No of dim of arr 1
shape of arr (6L,)
Size of arr 6
data type  of arr 1
Length of array is  6


## Accessing arrays 


In [18]:
print arr
print arr[0]
print arr[1] + arr[2]

[1 2 2 3 4 5]
1
4


## Accessing 2d arrays 
## using comas 
## arr[upper_index,lower_index]

In [24]:
arr_2d=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print arr_2d  

print arr_2d[0,1]
print arr_2d[1,2]
print arr_2d[0,5]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
2
9
6


## Accessing 3d arrays

In [27]:
ARR = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print ARR

print ARR[0, 1, 2]
print ARR[0, 0, 0]
print ARR[1, 1, 1]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6
1
11


In [32]:
print ARR[1, -1]
print ARR[0, -1]
print ARR[1, -2]
print ARR[0, -2]

[10 11 12]
[4 5 6]
[7 8 9]
[1 2 3]


## Slicing arrays

In [4]:
a1 = np.array([1,2,2,3,4,5])
print a1[0:5:2]

[1 2 4]


In [5]:
a2=np.array([1,2,3,4,5,6,7,8,9,10])
print a2[4:]

[ 5  6  7  8  9 10]


In [14]:
a2=np.array([1,2,3,4,5,6,7,8,9,10])
print a2[:5]
print a2[-4:-1]
print a2[1:9:3]
print a2[-1:-4:-1]
print a2[-4:-1:1]

[1 2 3 4 5]
[7 8 9]
[2 5 8]
[10  9  8]
[7 8 9]


## Slicing 2D arrays

In [19]:
a3 = np.array([[11,10,9,8],[7,6,5,4]])
print a3[0,1:4]
print a3[1,1:4]
print a3[-1,-3:-1]

[10  9  8]
[6 5 4]
[6 5]


In [30]:
a4 = np.array(['apple', 'banana', 'cherry'])
a5 = np.array([["kd","gaurav","vaish","ayush"],["prajwal","lokesh","adi"]])
a6 = np.array([1, 2, 3, 4])

print a6.dtype 
print a4.dtype
print a5.dtype

#converting arrays data type
a7 = np.array([1, 2, 3, 4], dtype='S')
print(a7)
print(a7.dtype)


int32
|S6
object
['1' '2' '3' '4']
|S1


## astype()

In [33]:
a8 = np.array([1.1, 2.1, 3.1])

new_a8 = a8.astype(int)

print a8.dtype
print new_a8.dtype
print new_a8

float64
int32
[1 2 3]


In [34]:
a9 = np.array([1, 0, 3])

new_a9 = a9.astype(bool)

print(a9.dtype)
print(new_a9.dtype)
print new_a9

int32
bool
[ True False  True]


In [3]:
A1= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,13,14,15,16,17,18,19,20])

newarr = A1.reshape(4,5)
print newarr

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


# Creating Array with differnet methods 


## Arrange

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
b = np.zeros((2,), dtype=[('x', 'float'), ('y', 'int')])
print b 


[(0., 0) (0., 0)]


## Linspace()
Syntax :numpy.linspcae(start,stop,num=50,restep,endpoint,dtype,axis)

In [14]:
frr = np.arange(10) 
print frr

frr1 = np.linspace(0,9,5)
print
print frr1

frr2 = np.linspace(0,9,9)
print
print frr2

frr3 = np.linspace(0,9,9,endpoint=False )
print
print frr3

frr4 = np.linspace(0,9,9,endpoint=False,dtype="string" )
print
print frr4
 




[0 1 2 3 4 5 6 7 8 9]

[0.   2.25 4.5  6.75 9.  ]

[0.    1.125 2.25  3.375 4.5   5.625 6.75  7.875 9.   ]

[0. 1. 2. 3. 4. 5. 6. 7. 8.]

['0.0' '1.0' '2.0' '3.0' '4.0' '5.0' '6.0' '7.0' '8.0']


## np.zeros

In [20]:
zero_arr=np.zeros([1,2],dtype="float")
print zero_arr
zero_arr2=np.zeros([7],dtype="float")
print zero_arr2
zero_arr3=np.zeros([4,5],dtype="float")
print zero_arr3

[[0. 0.]]
[0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## np.eye(R,C,k,dtype)
bydefault R=C , k>0 -> diagonal k upar else niche 

In [28]:
err = np.eye(6,6,k=0)
print err
print

err = np.eye(6,6,k=1)
print err
print

err = np.eye(6,6,k=2)
print err
print

err = np.eye(6,6,k=-1)
print err
print

err = np.eye(6,6,k=-2)
print err
print

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]

[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]



## Ones

In [7]:
orr = np.ones(8)
print orr
print

orr = np.ones([2,1])
print orr
print

norr = np.ones([5,5])
print norr


[1. 1. 1. 1. 1. 1. 1. 1.]

[[1.]
 [1.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## MAX,MIN,ARGMAX,ARGMIN

In [43]:
a = np.arange(10).reshape(2,5)
print a
print 
print a.max()
print a.min()
print
print np.argmax(a)
print np.argmin(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]

9
0

9
0


# EMPTY and FULL  ARRAY

In [48]:
a=np.arange(10)
# b=np.empty(R,C)
b=np.empty([4,3])
#full 
c=np.full((3,4),5)
print a
print b
print c




[0 1 2 3 4 5 6 7 8 9]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


# VECTOR
np.array(list)

In [52]:
lst = [1,2,3,4,5]
vector = np.array(lst)
print vector

[1 2 3 4 5]


## Arthimatic operation on vector 

In [56]:
lst = [2,4,6,8,10]
lstt = [12,16,18,24,20]
vector_1 = np.array(lst)
vector_2 = np.array(lstt)
print vector_1,vector_2

print "Addition of two vectors",vector_1 + vector_2
print "Subtraction  of two vectors",vector_1 - vector_2
print "Multiplication of two vectors",vector_1 * vector_2
print "Division of two vectors",vector_2 / vector_1
print 
print "Dot Product of two vectors ",vector_1.dot(vector_2)
print
print "Multilication of vector ith scaler",vector_1*2

[ 2  4  6  8 10] [12 16 18 24 20]
Addition of two vectors [14 20 24 32 30]
Subtraction  of two vectors [-10 -12 -12 -16 -10]
Multiplication of two vectors [ 24  64 108 192 200]
Division of two vectors [6 4 3 3 2]

Dot Product of two vectors  588

Multilication of vector ith scaler [ 4  8 12 16 20]


# APPENDING VALUES

## np.apped() & np.concatenate()

In [73]:
array_0=np.arange(6)
print array_0

new_array_0=np.append(array_0,[70])
print new_array_0

print

array1=np.arange(6)
concate_array = np.concatenate((array_0,array1),axis=0)
print concate_array

print 

array3=np.arange(6)
concate_array3 = np.concatenate((array_0,array1),axis=0)
print concate_array3

array2=np.array([100,109,108,107,100,120])
concate_array2 = np.concatenate([array1]+array2)
print concate_array2



[0 1 2 3 4 5]
[ 0  1  2  3  4  5 70]

[0 1 2 3 4 5 0 1 2 3 4 5]

[0 1 2 3 4 5 0 1 2 3 4 5]
[100 110 110 110 104 125]


## Appending array with array 

In [75]:
array4=np.arange(6)
array5 = np.arange(10)
new_apended_arr= np.append(array4,array5)
print new_apended_arr

[0 1 2 3 4 5 0 1 2 3 4 5 6 7 8 9]


# Swapping Coumns 


# Stack(h,v,d)

In [12]:
# stack((arr1,arr2))
ar1d=np.arange(10)
ar1d_2=np.arange(10)
new_1d= np.vstack((ar1d,ar1d_2))
s_1d= np.hstack((ar1d,ar1d_2))
T_1d= np.dstack((ar1d,ar1d_2))
print new_1d
print
print s_1d
print 
print T_1d

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]

[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]

[[[0 0]
  [1 1]
  [2 2]
  [3 3]
  [4 4]
  [5 5]
  [6 6]
  [7 7]
  [8 8]
  [9 9]]]


In [16]:
ar2d=np.arange(10).reshape(5,2)
print ar2d
ar2d_2=np.arange(10).reshape(5,2)
print ar2d_2
new_2d= np.vstack((ar2d,ar2d_2))
s_2d= np.hstack((ar2d,ar2d_2))
T_2d= np.dstack((ar2d,ar2d_2))
print new_1d
print
print s_1d
print 
print T_1d

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]

[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]

[[[0 0]
  [1 1]
  [2 2]
  [3 3]
  [4 4]
  [5 5]
  [6 6]
  [7 7]
  [8 8]
  [9 9]]]


# np.block
Combine multipe arrays

In [36]:
ar1d_3=np.arange(10)
ar1d_4=np.arange(10)
print ar1d
print
print ar1d_2
print
print ar1d_3
print
print ar1d_4
print
multiple = np.block([[ar1d,ar1d_2],[ar1d_3,ar1d_4]])
print multiple
print

    

[0 1 2 3 4 5 6 7 8 9]

[0 1 2 3 4 5 6 7 8 9]

[0 1 2 3 4 5 6 7 8 9]

[0 1 2 3 4 5 6 7 8 9]

[[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]]



# Splitting arrays 
## syntax : np.split(array_name,no_of_subarrays,axis)

In [38]:
array6=np.arange(4)
sub_arr=np.split(array6,2)#equal sub arrays
print sub_arr

array7=np.arange(5)
sub_arr1=np.array_split(array7,2)#unequal sub arrays
print sub_arr1

array8=np.arange(6).reshape(2,3)
sub_ar22=np.split(array8,2)
print sub_ar22

[array([0, 1]), array([2, 3])]
[array([0, 1, 2]), array([3, 4])]
[array([[0, 1, 2]]), array([[3, 4, 5]])]


## Comapring  arrays 
1, by == 

2, method 


In [85]:
if array6==array7:
    print "equal"
else:
    print "not-Equal"

not-Equal


C:\ProgramData\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


In [94]:
array9=np.array([2,4,63,76,7])
array10=np.array([14,5,67,3,7])
print np.greater(array9,array10)
print np.greater(array10,array9)
print
print np.greater_equal(array9,array10)
print np.greater_equal(array10,array9)
print
print np.less(array9,array10)
print np.less(array10,array9)
print 
print np.less_equal(array9,array10)
print np.less_equal(array10,array9)

[False False False  True False]
[ True  True  True False False]

[False False False  True  True]
[ True  True  True False  True]

[ True  True  True False False]
[False False False  True False]

[ True  True  True False  True]
[False False False  True  True]


# UNION of Arrays 

In [95]:
union=np.union1d(array9,array10)
print union 

[ 2  3  4  5  7 14 63 67 76]


In [98]:
arr2d1=np.array([[1,2,2],[1,2,3]])
arr2d2=np.array([[4,5,9],[6,7,8]])
union2=np.union1d(arr2d1,arr2d2)
print union2 

[1 2 3 4 5 6 7 8 9]
